# Generated by Django 6.1 on 2026-09-03 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission FAQ',
                'verbose_name_plural': 'Admission FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Admission Step',
                'verbose_name_plural': 'Admission Roadmap Steps',
                'ordering': ['step_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CampusFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='bi bi-building', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Campus Facility',
                'verbose_name_plural': 'Campus Facilities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('inquiry_type', models.CharField(default='General', max_length=100)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by administration (never shown publicly)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='bi bi-shield-lock-fill', help_text='Bootstrap Icon class name (e.g. bi bi-trophy-fill, bi bi-hammer)', max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Department of Sciences', max_length=150)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Faculty'), ('OPERATIONAL', 'Operational / Boarding Division'), ('SUPPORT', 'Student Support / Welfare')], default='ACADEMIC', max_length=20)),
                ('badge_text', models.CharField(default='Core STEM', help_text='e.g. Core STEM, Analytical, Welfare', max_length=100)),
                ('subjects', models.CharField(blank=True, help_text='e.g. Biology • Chemistry • Physics', max_length=300)),
                ('description', models.TextField()),
                ('hod_name', models.CharField(default='[HOD Name]', help_text='Head of Department', max_length=150)),
                ('facilities_summary', models.CharField(blank=True, default='Dedicated Laboratories', max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reporter_type', models.CharField(max_length=100)),
                ('feedback_category', models.CharField(max_length=150)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('desired_outcome', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal review findings and committee notes (confidential)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback & Grievance',
                'verbose_name_plural': 'Feedback & Grievance Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(help_text='e.g. academics, sports, campus, events', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. BOM Chairperson, Chief Principal, Deputy Principal', max_length=150)),
                ('category', models.CharField(choices=[('BOM', 'Board of Management'), ('ADMIN', 'School Administration'), ('FACULTY', 'Senior Master / Head of Section')], default='ADMIN', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Brief professional bio or portfolio description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('photo_url', models.URLField(blank=True, help_text='Optional fallback image URL', max_length=500)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Leadership Member',
                'verbose_name_plural': 'Leadership & Administration',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolCircular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Term 1 Parent Circular.pdf', max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='circulars/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'School Circular',
                'verbose_name_plural': 'Official Circulars & Downloads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('time', models.CharField(default='9:00 AM - 1:00 PM', max_length=100)),
                ('venue', models.CharField(default='School Main Hall', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'School Event',
                'verbose_name_plural': 'School Events & Calendar',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Kigumo Bendera High School', max_length=200)),
                ('subtitle', models.CharField(default="High School • Murang'a", max_length=200)),
                ('motto', models.CharField(default='Shaping Minds. Building Character. Inspiring Excellence.', help_text='Official school motto/tagline', max_length=250)),
                ('about_short', models.TextField(default='A premier government-aided secondary boarding school dedicated to nurturing young minds into intellectual giants, disciplined leaders, and ethically grounded global citizens.', help_text='Short description displayed in the footer and intro widgets')),
                ('about_full', models.TextField(default="Kigumo Bendera High School is a distinguished public secondary boarding school situated in the tranquil, lush environment of Kigumo, Murang'a County. Designed to cultivate academic ambition and principled character, the school has nurtured generations of young scholars into national leaders, engineers, doctors, teachers, entrepreneurs, and public servants.", help_text='Full background story displayed on the About Us page')),
                ('vision', models.TextField(default='To be a premier national center of holistic secondary education, producing principled, innovative, and competitive scholars.')),
                ('mission', models.TextField(default='To deliver quality, inclusive, and transformative education through rigorous academic mentorship, disciplined co-curricular engagements, and moral instruction.')),
                ('phone', models.CharField(default='0710336023', help_text='Primary telephone number (displayed as 0710336023, links to tel:+254710336023)', max_length=50)),
                ('email', models.EmailField(default='kabiraallan79@gmail.com', help_text='Primary school email address (links to mailto:kabiraallan79@gmail.com)', max_length=254)),
                ('physical_address', models.CharField(default="Kigumo Sub-County, Murang'a County, Kenya", max_length=300)),
                ('postal_address', models.CharField(blank=True, default='P.O. Box ... Kigumo, Kenya', max_length=200)),
                ('office_hours', models.CharField(default='Mon - Fri: 8:00 AM - 5:00 PM', max_length=150)),
                ('term_status', models.CharField(default='Term 1 In Session', help_text='Top bar status badge text', max_length=100)),
                ('registration_code', models.CharField(blank=True, default='[School Registration Code]', max_length=100)),
                ('hero_badge', models.CharField(default='Premier Center of Academic & Moral Excellence', max_length=200)),
                ('hero_headline', models.CharField(default='KIGUMO BENDERA HIGH SCHOOL', max_length=200)),
                ('hero_subtext', models.TextField(default='"Shaping Minds. Building Character. Inspiring Excellence." A premier secondary boarding school in Murang\'a County dedicated to transformative education and exemplary leadership.')),
                ('stat_students', models.CharField(default='1,200+', max_length=50, verbose_name='Enrolled Scholars')),
                ('stat_teachers', models.CharField(default='45+', max_length=50, verbose_name='Experienced Tutors')),
                ('stat_university', models.CharField(default='100%', max_length=50, verbose_name='University Prep')),
                ('stat_clubs_sports', models.CharField(default='28+', max_length=50, verbose_name='Clubs & Sports')),
                ('principal_name', models.CharField(default="[Principal's Name]", max_length=150)),
                ('principal_title', models.CharField(default='Chief Principal', max_length=150)),
                ('principal_quote', models.TextField(default='At Kigumo Bendera High School, we believe that education is not merely the transmission of facts, but the ignition of intellect and the steadfast cultivation of character.')),
                ('principal_desk_note', models.TextField(default="Welcome to Kigumo Bendera High School. For years, our institution has stood as a beacon of academic rigor, self-discipline, and holistic transformation in Murang'a County. Our students are challenged in state-of-the-art laboratories, mentored by passionate faculty, and empowered through rich sporting and co-curricular programs.")),
                ('principal_photo', models.ImageField(blank=True, null=True, upload_to='principal/')),
                ('logo', models.ImageField(blank=True, help_text='Custom logo if overriding SVG default', null=True, upload_to='branding/')),
                ('facebook_url', models.URLField(blank=True, default='#')),
                ('twitter_url', models.URLField(blank=True, default='#')),
                ('youtube_url', models.URLField(blank=True, default='#')),
                ('linkedin_url', models.URLField(blank=True, default='#')),
                ('admission_hotline', models.CharField(default='0710336023', max_length=50)),
                ('boarding_levy_guideline', models.CharField(blank=True, default='[Insert Ministry-Approved Fee: KSh. XX,XXX per annum]', max_length=200)),
                ('bank_payment_details', models.CharField(blank=True, default='[Bank Name / Branch / Account Number]', max_length=250)),
            ],
            options={
                'verbose_name': 'School Profile & General Information',
                'verbose_name_plural': 'School Profile & General Information',
            },
        ),
        migrations.CreateModel(
            name='SportsDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Football (Soccer), Rugby 7s & 15s', max_length=100)),
                ('subtitle', models.CharField(default='Competitive Squad', max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='bi bi-trophy', max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Sports Discipline',
                'verbose_name_plural': 'Sports & Athletics Disciplines',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Science & Robotics Club', max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='bi bi-robot', max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Student Club / Society',
                'verbose_name_plural': 'Student Clubs & Societies',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback image URL if no file uploaded', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='schoolapp.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('summary', models.TextField(help_text='Short abstract displayed in cards')),
                ('content', models.TextField(blank=True, help_text='Full article narrative')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback image URL if no file uploaded', max_length=500)),
                ('author', models.CharField(default='Office of the Principal', max_length=150)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured headline banners')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='schoolapp.newscategory')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles & Announcements',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
